export default {
  borderRadius: {
    borderRadiusNone: '0',
    borderRadiusSM: '5px',
    borderRadiusMD: '10px',
    borderRadiusLG: '18px',
    borderRadiusXL: '24px',
    borderRadiusCircle: '50%',
  },
  font: {
    family:
      "Poppins, -apple-system, BlinkMacSystemFont, 'Segoe UI', Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif",
    fontWeightLight: '300',
    fontWeightRegular: '400',
    fontWeightSemiBold: '500',
    fontWeightBold: '700',
    sizes: {
      xxsmall: '1rem',
      xsmall: '1.2rem',
      small: '1.4rem',
      medium: '1.6rem',
      large: '1.8rem',
      xlarge: '2.0rem',
      xxlarge: '2.4rem',
      xxxlarge: '2.8rem',
      huge: '3.0rem',
      xhuge: '3.4rem',
      xxhuge: '3.8rem',
      xxxhuge: '4.2rem',
    },
  },
  gradient: {
    gradientColorBottom:
      'linear-gradient( to bottom, #f44336 0%, #5e35b1 100%)',
    gradientColorLeft: 'linear-gradient( to left, #f44336 0%, #5e35b1 100%)',
    gradientGreyBottom: 'linear-gradient( to bottom, #818386 0%, #5e35b1 #aaa)',
  },
  grid: {
    container: '130rem',
    gutter: '2.4rem',
  },
  sizes: {
    xsmall: '1.2rem',
    small: '1.4rem',
    medium: '1.6rem',
    large: '1.8rem',
    xlarge: '2.0rem',
    xxlarge: '2.4rem',
    xxxlarge: '2.8rem',
    huge: '3.0rem',
    xhuge: '3.4rem',
    xxhuge: '3.8rem',
    xxxhuge: '4.2rem',
  },
  lineHeight: {
    lineHeightSM: '100%',
    lineHeightMD: '110%',
    lineHeightLG: '120%',
    lineHeightUL: '150%',
  },
  colors: {
    blue: '#5429CC',
    blueLigth: '#6933FF',
    green: '#33CC95',
    messageError: '#E62E4D',
    shap: '#FFFFFF',
    title: '#363F5F',
    text: '#969CB2',
    background: '#E5E5E5',
    grey: '#e7e9ee',
    greyLigth: '#D7D7D7',
    blackSemiDark: '#A8A8B3',
    greyDark: '#969CB3',
  },
  spacings: {
    xxsmall: '0.8rem',
    xsmall: '1.6rem',
    small: '2.4rem',
    medium: '3.2rem',
    large: '4.0rem',
    xlarge: '4.8rem',
    xxlarge: '5.6rem',
  },
  layers: {
    base: 10,
    menu: 20,
    overlay: 30,
    modal: 40,
    alwaysOnTop: 50,
  },
  screen: {
    screenXS: '425px',
    screenSM: '768px',
    screenMD: '1000px',
    screenLG: '1400px',
    screenXL: '2560px',
  },
  transition: {
    default: '0.3s ease-in-out',
    fast: '0.1s ease-in-out',
  },
};
